version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    container_name: todo-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=todo_db
    depends_on:
      - mongo
volumes:
  mongo_data: